### ISSUE TITLE
Does not handle methods not annotated with @Path

### ISSUE THREAD

**Issue by newjam** [WorksApplications/js-generator-for-jax-rs#4]
It is perfectly valid according to jax-rs spec to have a method in a resource that is not annotated with @Path. For example:

``` java
@Path("/foo")
interface MyResource {
    @GET
    Foo getFoo();
}
```

This would cause:

[ERROR] Failed to execute goal jp.co.worksap.jax_rs:js-generator-for-jax-rs:1.0.0:generate (default) on project edu-api-demo: InvocationTargetException occurs: The annotated element, public my.package.MyResource my.package.MyResource.getFoo() is not annotated with @Path -> [Help 1]

**Comment by KengoTODA** [comment]
Thanks for your contribution,

I think it is NOT supported by JAX_RS specification that adding annotation onto interface. I'll quote [the discussion at Jira](https://java.net/jira/browse/JAX_RS_SPEC-19):

> JAX-RS does not support inheritance of annotations applied to interface types. The statement quoted refers to interfaces methods (and should be clarified). Annotations such as @Path are intended for resource classes (which by definition must be concrete classes).

So currently we have no plan to support this case. I recommend you to modify your code to follow JAX_RS specification strictly.
